### ISSUE TITLE
Add notes in documentation about tests triggered by build.

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/django-ex#58] opened 2016-09-01 01:28 UTC
A section should be added to the documentation about how tests are being triggered by a "postCommit" in the build configuration. It is important to highlight it because its presence can break builds in a confusing way if people copy this repo as an example and change around how databases are setup and remove the fallback to SQLite.

Worst case would be someone who changed the code such that database information was available during the build phase. In this case they could run the tests against an external production database, which could be really bad as could be destructive of data.

So better to highlight what is being done with running tests during the build and how it is done.

This issue came about because a real world user did remove the fallback to SQLite and so all their builds were then failing and they had no idea.

**Comment by bparees** [comment] 2016-09-01 01:36
Sounds like part of the issue is that our logging/etc is not doing a good job of indicating the build failed because the postcommit tests failed?

also i take it they copied the template and not just the source?

**Comment by GrahamDumpleton** [comment] 2016-09-01 01:38
They copied both but then overrode DATABASES in settings module.

* https://github.com/CGPartners2016/ratescentral/blob/master/project/settings.py#L93

**Comment by rhcarvalho** [comment] 2016-11-30 16:48
This seems to be a problem common to all language/framework examples?

Build hooks are documented here: https://docs.openshift.org/latest/dev_guide/builds.html#build-hooks

Perhaps the suggestion here is to update all examples to warn about database settings and automatic test execution? I am not sure that would be very effective in preventing people from doing things like pointing to a production database.
If they then run the tests in their own dev machines they would as well destroy data.

**Comment by rhcarvalho** [comment] 2017-02-24 19:10
@bparees please reassign.

**Closed** 2017-03-29 15:34 UTC
