### ISSUE TITLE
Found "SyntaxError: invalid syntax" while deploying through openshift/python-27-centos7 registry

### ISSUE THREAD

**Issue by amitkrout** [openshift/django-ex#49] opened 2016-07-05 14:10 UTC
Found the below error in build logs of django-ex 
```
File "/tmp/pip-build-UPwlfC/gunicorn/gunicorn/workers/_gaiohttp.py", line 78
yield from self.wsgi.close()
^
SyntaxError: invalid syntax
```
Steps to reproduce:
1. Create a new project (oc new-project python-test)
2. Deploy the new app (oc new-app openshift/python-27-centos7~https://github.com/openshift/django-ex) 
3. Go to the build logs (oc logs -f bc/django-ex)
3. Build is successful but in the build logs found an error as above

**Comment by bparees** [comment] 2016-07-05 14:13
@soltysh @rhcarvalho this has nothing to do w/ the image, right?  something bad in the gunicorn libs?

**Comment by soltysh** [comment] 2016-07-05 14:39
It's the same as https://github.com/sclorg/s2i-python-container/issues/117 In short we need newer pip in that image.

**Comment by bparees** [comment] 2016-07-05 15:11
thanks @soltysh 

closing as dupe of https://github.com/sclorg/s2i-python-container/issues/117

**Closed by bparees** 2016-07-05 15:11 UTC
